title: Andreas Remdt
url: "https://andreasremdt.com" 

markdown: kramdown
permalink: /blog/:year/:month/:day/:title/

collections:
  projects:
    output: true
    permalink: /:collection/:name/

include:
  - _headers